import type { Localized } from "@/lib/locale";

function L(zh: string, en: string): Localized {
  return { zh, en };
}

export const copy = {
  brandZh: "你好校园",
  brandEn: "NihaoCampus",
  explore: L("城市与校区", "Cities & campuses"),
  njuXianlin: L("南大仙林校区", "NJU Xianlin"),
  browse: L("逛一逛", "Browse"),
  about: L("关于", "About"),
  sampleCity: L("示例城市：南京", "Sample city: Nanjing"),
  language: L("语言", "Language"),
  chinese: L("中文", "中文"),
  english: L("English", "English"),
  testBannerAria: L("测试版本说明", "Test preview notice"),
  testBannerLead: L("测试预览版：", "Test preview:"),
  testBannerBody: L(
    "城市、价格、成员和帖子均为演示数据，不代表学校或真实用户，请勿据此办理申请、签证或作出生活决策。",
    "Cities, prices, members and posts are demo data. They are not from a university or a real person. Do not use them for applications, visas, or life decisions.",
  ),
  footerBody: L(
    "本站当前处于测试阶段。城市、校区、价格、成员与帖子均为演示数据，不代表学校、机构或真实用户。",
    "This site is a test preview. Cities, campuses, prices, members and posts are demo data, not a university, an agency, or a real person.",
  ),
  footerLegal: L(
    "演示内容可能不准确或已过时。办签证、居留许可等事项，请以学校国际处和当地出入境管理部门发布的信息为准。",
    "Demo copy can be wrong or out of date. For visas and residence permits, follow the international office and the local exit-entry bureau.",
  ),
  signIn: L("登录", "Sign in"),
  join: L("加入", "Join"),
  myPage: L("我的主页", "My page"),
  editProfile: L("编辑资料", "Edit profile"),
  signOut: L("退出登录", "Sign out"),
  signedOut: L("已退出登录", "Signed out"),
  home: L("首页", "Home"),
  places: L("地点", "Places"),
  breadcrumb: L("面包屑", "Breadcrumb"),
  pageNav: L("页面导航", "On this page"),
  kicker: L("你好校园 · 来华留学生的城市与校区指南", "NihaoCampus · a campus guide for students coming to China"),
  homeH1: L(
    "按城市和校区整理的来华留学指南：多少钱、怎么落地、附近吃什么、谁已经在那儿。",
    "A city-by-city, campus-by-campus guide to studying in China: what it costs, how to land, where to eat, and who is already there.",
  ),
  startPicking: L("开始挑校区", "Start with a campus"),
  sampleCityCta: L("先看样板城市", "Start with the sample city"),
  cities: L("城市", "Cities"),
  campuses: L("校区", "Campuses"),
  members: L("成员", "Members"),
  countries: L("国家", "Countries"),
  threads: L("帖子", "Threads"),
  discoverTitle: L("城市与校区", "Cities & campuses"),
  discoverLead: L(
    "综合评分是十项打分的平均值，月预算不含学费。先按城市挑，再进校区看落地清单。",
    "The overall score is the mean of ten ratings. Monthly budgets exclude tuition. Pick a city, then open a campus landing checklist.",
  ),
  exampleLead: L(
    "每个城市都会按这个深度写：具体的地址、具体的价格、具体的坑。南京是第一个写完的。",
    "Every city is written at this depth: real addresses, real prices, real traps. Nanjing is the first one finished.",
  ),
  exampleTitle: L("先看南京", "Start with Nanjing"),
  threadsTitle: L("最新讨论", "Latest threads"),
  threadsLead: L(
    "留言板上刚发出来的帖子。点进去就是那个校区或城市的社区。",
    "Fresh posts from the boards. Open one to land in that campus or city community.",
  ),
  listedCampuses: L("已收录", "Listed"),
  fromBudget: L("起", "from"),
  comfortable: L("舒适", "Comfortable"),
  intlStudents: L("国际生", "Intl. students"),
  nCountries: L("个国家", "countries"),
  monthlyBudget: L("月预算", "Monthly budget"),
  overall: L("综合评分", "Overall"),
  overallHint: L("十项平均，满分 100", "Mean of ten scores, out of 100"),
  population: L("人口", "Population"),
  millions: L("百万", "million"),
  metro: L("地铁", "Metro"),
  metroLines: L("条线", "lines"),
  julJan: L("夏天 / 冬天", "Jul / Jan"),
  julJanHint: L("月均最高 / 最低", "Monthly high / low"),
  scores: L("十项评分", "Scores"),
  scoresLead: L(
    "1 分很差，5 分很好。悬停或看小字了解每项的口径。",
    "1 is rough, 5 is strong. The line under each bar is how that score is defined.",
  ),
  highlights: L("亮点与提醒", "Highlights"),
  climate: L("十二个月的天气", "Twelve months of weather"),
  climateLead: L(
    "决定你要不要带羽绒服，以及夏天会不会想逃。",
    "This is how you decide on a down jacket, and whether July will make you want to leave.",
  ),
  climateCampusLead: L(
    "全年月均最高、最低气温、雨天数和空气质量。",
    "Monthly high, low, rain days, and air quality.",
  ),
  visa: L("出入境管理局", "Exit-Entry Administration"),
  visaLead: L(
    "南京有多个受理点，去哪一个取决于学校和住址。每个校区的落地清单指向自己那个厅。",
    "Nanjing has several halls. Which one you use depends on the school and your address. Each campus checklist points at its hall.",
  ),
  arrivals: L("抵达与往返", "Getting in and out"),
  arrivalsLead: L(
    "机场、高铁站到市区，以及去邻近城市的时间和价格。",
    "Airport and rail into the city, plus time and price to nearby cities.",
  ),
  cityCampusesLead: L(
    "每个校区都有自己的落地清单、周边和住哪儿。",
    "Each campus has its own landing checklist, nearby spots, and places to live.",
  ),
  facts: L("概况", "Quick facts"),
  money: L("花多少钱", "Money"),
  moneyLead: L(
    "月预算不含学费。下面是这个校区的实际单价，美元按 1:7.1 粗略换算。",
    "Monthly budgets exclude tuition. Unit prices below are for this campus. USD is a rough 1:7.1 conversion.",
  ),
  landing: L("落地清单", "Landing checklist"),
  landingLead: L(
    "9 步，按顺序做。每一步写明去哪、带什么、花多久，中文地址可以直接复制给司机。",
    "Nine steps, in order. Each one says where to go, what to bring, and how long it takes. The Chinese address copies for a driver.",
  ),
  spots: L("周边", "Around campus"),
  spotsLead: L(
    "先选今天要干什么，再按类别看。店名和价格能核到官方页的才写上，其余标未核实。",
    "Pick what you need to do today, then filter by category. Names and prices appear only when a page we checked names them.",
  ),
  situations: L("今天要干什么", "What you need today"),
  orientation: L("校区方位", "Campus orientation"),
  orientationLead: L(
    "方块是校区。四个方向来自南航公开页上的门和分区，没有地图 SDK。步行分钟数官方页没写的就留空。",
    "The square is the campus. The four sides come from NUAA pages that name gates or zones. No map SDK. Walk minutes stay blank when the page does not publish them.",
  ),
  walkUnpublished: L("步行分钟未公布", "Walk minutes not published"),
  timeUnpublished: L("用时未公布", "Time not published"),
  fareUnpublished: L("费用未公布", "Fare not published"),
  dormYear: L("宿舍年费（招生简章）", "Dorm fee / year (brochure)"),
  filterBySituation: L("按今天要做的事筛选", "Filter by what you need today"),
  noSpotsHere: L("这一层还没有核过的地点。", "No verified place sits in this layer yet."),
  neighborhoods: L("住哪儿", "Where to live"),
  neighborhoodsLead: L(
    "住校外的话，附近这几片是同学们真正在住的地方。",
    "If you live off campus, these are the blocks students actually rent.",
  ),
  neighborhoodsOnCampus: L(
    "下面是后勤页上的校内宿舍分区，不是校外租房指南。",
    "These are on-campus dorm zones from the logistics pages, not an off-campus renting guide.",
  ),
  transport: L("交通", "Getting around"),
  transportLead: L(
    "从校门口出发到市中心、火车站、机场的时间和价格。",
    "Time and price from the campus gate to downtown, the rail station, and the airport.",
  ),
  verdict: L("优点与缺点", "The honest version"),
  faq: L("常见问题", "FAQ"),
  community: L("社区", "Community"),
  noticeCampus: L(
    "内容由在读学生维护，政策、价格和办公时间都会变。涉及签证、居留许可、住宿登记的事，行动前请再向学校国际处确认一次。",
    "Students keep this page. Policies, prices, and hours change. Reconfirm visas, residence permits, and police registration with the international office before you act.",
  ),
  noticeCity: L(
    "内容由在读学生维护，政策、价格和办公时间都会变。涉及签证、居留许可的事，行动前请再向学校国际处或出入境管理局确认一次。",
    "Students keep this page. Reconfirm anything visa-related with the international office or the exit-entry bureau.",
  ),
  noticePlace: L(
    "地址会变。出发前再向学校国际处确认一次。",
    "Addresses move. Reconfirm with the international office before you go.",
  ),
  mostPeople: L("多数人", "Most people"),
  perMonth: L("/ 月", "/ mo"),
  free: L("免费", "Free"),
  feeVaries: L("费用视情况", "Fee varies"),
  feeUnverified: L("费用未核实", "Fee not verified"),
  minutesOnSite: L("现场约 {n} 分钟", "About {n} min on site"),
  stepN: L("第 {n} 步 / {total}", "Step {n} / {total}"),
  bring: L("带上", "Bring"),
  tips: L("过来人的话", "Tips"),
  warning: L("注意", "Watch out"),
  copyAddress: L("复制中文地址给司机看", "Copy the Chinese address for the driver"),
  copied: L("已复制", "Copied"),
  copyFailed: L("复制失败，请长按文字手动复制", "Copy failed. Press and hold the text."),
  addressUnverified: L(
    "地址与时间未核实，出发前请与学校国际处确认",
    "Address and hours are unverified. Ask the international office before you go.",
  ),
  hours: L("办公时间", "Hours"),
  hoursUnknown: L("办公时间未核实", "Hours not verified"),
  appointment: L("要不要预约", "Appointment"),
  appointmentYes: L("需要预约", "Appointment required"),
  appointmentNo: L("不用预约", "No appointment"),
  appointmentUnknown: L("是否预约未核实", "Appointment not verified"),
  phone: L("电话", "Phone"),
  phoneUnknown: L("电话未核实", "Phone not verified"),
  maps: L("在地图里打开", "Open in maps"),
  amap: L("高德", "Amap"),
  baidu: L("百度", "Baidu"),
  googleMaps: L("Google Maps", "Google Maps"),
  checkedOn: L("核验于", "checked"),
  landingBacklinks: L("落地清单里的这一步", "This step on a landing checklist"),
  noLandingBacklinks: L("没有落地步骤指向这里。", "No landing step points here."),
  spotBacklinks: L("校区周边", "Around a campus"),
  noSpotBacklinks: L("没有校区把这里写进周边。", "No campus lists this as a nearby spot."),
  notes: L("经验", "Notes"),
  noNotes: L("还没有人在这里留下经验。", "Nobody has left a note here yet."),
  events: L("事件", "Events"),
  noEvents: L("还没有事件绑在这个地点。", "No events are tied to this place."),
  stepLink: L("第 {n} 步 {step} · {campus}", "Step {n} {step} · {campus}"),
  pros: L("优点", "What people love"),
  cons: L("缺点", "What wears you down"),
  studioRent: L("一居室月租", "Studio rent"),
  commute: L("通勤", "Commute"),
  goodFor: L("适合", "Good for"),
  minutes: L("{n} 分钟", "{n} min"),
  all: L("全部", "All"),
  filterByCategory: L("按类别筛选", "Filter by category"),
  walkMinutes: L("步行 {n} 分钟", "{n} min walk"),
  noSpend: L("不花钱", "No spend"),
  perPerson: L("人均 {price}", "About {price}"),
  location: L("位置", "Where"),
  walk: L("步行", "Walk"),
  price: L("价格", "Price"),
  englishOk: L("英语", "English"),
  climateScale: L(
    "柱子是月均最低到最高气温，-10°C 到 40°C",
    "The bar is monthly low to high, from -10°C to 40°C",
  ),
  rainDays: L("月雨天数", "Rain days / month"),
  aqiLegend: L("底部彩色数字是月均 AQI：", "The colour number is monthly AQI: "),
  aqiGood: L("优", "Good"),
  aqiOk: L("良", "Fair"),
  aqiLight: L("轻度", "Light"),
  aqiMid: L("中度+", "Mid+"),
  climateSr: L(
    "最高 {high}°C，最低 {low}°C，雨天 {rain} 天，AQI {aqi}",
    "High {high}°C, low {low}°C, {rain} rain days, AQI {aqi}",
  ),
  intlFrom: L("来自 {n} 个国家", "from {n} countries"),
  intlStatNote: L("口径见下", "See the counting note"),
  tuitionYear: L("学费 / 年", "Tuition / year"),
  taughtIn: L("授课语言", "Taught in"),
  founded: L("始建", "Founded"),
  dorm: L("宿舍", "Dorm"),
  dormYes: L("保证有床位", "A bed is guaranteed"),
  dormNo: L("不保证床位", "A bed is not guaranteed"),
  offCampus: L("校外住宿", "Off campus"),
  allowed: L("允许", "Allowed"),
  notAllowed: L("不允许", "Not allowed"),
  applyWindow: L("申请窗口", "Applications"),
  scholarships: L("奖学金", "Scholarships"),
  website: L("官网", "Website"),
  langZh: L("中文", "Chinese"),
  scoreGood: L("很好", "Strong"),
  scoreOk: L("不错", "Solid"),
  scoreMeh: L("一般", "Mixed"),
  scoreTitle: L("综合评分 {n} / 100", "Overall {n} / 100"),
  viewMode: L("查看方式", "View"),
  search: L("搜索", "Search"),
  searchCity: L(
    "搜城市、省份或拼音，例如 南京 / Nanjing",
    "Search a city, province, or pinyin, e.g. Nanjing",
  ),
  searchCampus: L(
    "搜大学、校区或城市，例如 东南大学 / SEU",
    "Search a university, campus, or city, e.g. SEU",
  ),
  clearSearch: L("清除搜索", "Clear search"),
  sort: L("排序", "Sort"),
  monthlyCap: L("月预算", "Monthly cap"),
  unlimited: L("不限", "Any"),
  clearFilters: L("清除筛选", "Clear filters"),
  resultCount: L("{n} 个{noun} · 按{sort}排序", "{n} {noun} · sorted by {sort}"),
  noResults: L("没有符合这些条件的{noun}", "No {noun} match these filters"),
  noResultsHint: L(
    "放宽预算、去掉一个筛选，或者换个关键词试试。",
    "Raise the budget cap, drop a chip, or try another word.",
  ),
  otherViewHas: L("{label}里有 {n} 个结果", "{label} has {n} hits"),
  clearAll: L("清除全部筛选", "Clear all filters"),
  byCity: L("按城市", "By city"),
  byCampus: L("按校区", "By campus"),
  nounCity: L("城市", "cities"),
  nounCampus: L("校区", "campuses"),
  justNow: L("刚刚", "just now"),
  minutesAgo: L("{n} 分钟前", "{n}m ago"),
  hoursAgo: L("{n} 小时前", "{n}h ago"),
  yesterday: L("昨天", "yesterday"),
  daysAgo: L("{n} 天前", "{n}d ago"),
  monthsAgo: L("{n} 个月前", "{n}mo ago"),
  yearsAgo: L("{n} 年前", "{n}y ago"),
  meetHere: L("在这里见面", "Meet here"),
  boardOf: L("{title} 的留言板", "The {title} board"),
  emptyBoard: L("还没有人留言", "No posts yet"),
  emptyBoardHint: L(
    "把你刚踩过的坑写下来，下一个到这个校区的人会谢谢你。上面就能发第一条。",
    "Write down a trap you just hit. The next student at this campus will thank you. The form above is the first post.",
  ),
  post: L("发帖", "Post"),
  posting: L("正在发布…", "Posting…"),
  publish: L("发布", "Publish"),
  postTitlePh: L("标题，比如：仙林办银行卡要带什么", "Title, e.g. What to bring to open a bank account"),
  postBodyPh: L("把经过写清楚，后来的人就能少走一步。", "Write what actually happened so the next person skips a step."),
  replies: L("{n} 条回复", "{n} replies"),
  noReplies: L("还没有回复，来写第一条。", "No replies yet. Write the first one."),
  replyPh: L("写一条回复…", "Write a reply…"),
  sending: L("发送中…", "Sending…"),
  reply: L("回复", "Reply"),
  needSignInPost: L("登录后才能发帖", "Sign in to post"),
  needSignInReply: L("登录后才能回复", "Sign in to reply"),
  somethingWrong: L("出了点问题，再试一次", "Something broke. Try again."),
  signInTitle: L("登录 NihaoCampus", "Sign in to NihaoCampus"),
  joinTitle: L("加入 NihaoCampus", "Join NihaoCampus"),
  signInLead: L("发帖和回帖需要登录后才能看。", "Sign in to post and reply."),
  joinLead: L("填一次资料，就能在校区留言板上发言。", "Fill this in once, then you can post on a campus board."),
  emailOrUser: L("邮箱或用户名", "Email or username"),
  password: L("密码", "Password"),
  signingIn: L("正在登录…", "Signing in…"),
  noAccount: L("还没有账号？", "No account yet?"),
  registerOne: L("注册一个", "Create one"),
  displayName: L("你想让大家怎么称呼你", "What should people call you"),
  username: L("用户名", "Username"),
  email: L("邮箱", "Email"),
  passwordHint: L("至少 8 位", "At least 8 characters"),
  next: L("下一步", "Next"),
  back: L("上一步", "Back"),
  whereFrom: L("你来自哪里", "Where are you from"),
  pickCountry: L("选择国家", "Select a country"),
  yourStatus: L("你现在的状态", "Your status"),
  whichCampus: L("哪个校区", "Which campus"),
  undecided: L("还没决定", "Not decided yet"),
  pickCampus: L("选择校区", "Select a campus"),
  creating: L("正在创建…", "Creating…"),
  createAccount: L("创建账号", "Create account"),
  haveAccount: L("已经有账号了？", "Already have an account?"),
  goSignIn: L("去登录", "Sign in"),
  stepAccount: L("第 1 步 账号", "Step 1 · Account"),
  stepIdentity: L("第 2 步 你的身份", "Step 2 · You"),
  welcomeBack: L("欢迎回来", "Welcome back"),
  registered: L("注册成功，欢迎加入", "You're in. Welcome."),
  notFound: L("没有这个页面", "This page is not here"),
  notFoundBody: L("链接可能写错了，或者这个城市还没写。", "The link may be wrong, or this city is not written yet."),
  backHome: L("回到首页", "Back home"),
  sourceChecked: L("{kind} 核验于 {date}", "{kind} · checked {date}"),
  howToGetThere: L("从各校区怎么去", "How to get there"),
  howToGetThereLead: L("核验过的路线会写在这里。现在还没有。", "Verified routes will show up here. None yet."),
  noVerifiedRoute: L(
    "还没有从校门出发的核验路线。出发前问国际处或看地图深链。",
    "No verified route from a campus gate yet. Ask the international office or use the map links.",
  ),
  whoUses: L("谁在用这个地点", "Who uses this place"),
  listedCampusesCount: L("{n} 个校区", "{n} campuses"),
  enterCity: L("进入{name}", "Open {name}"),
  cityCampuses: L("{name}的校区", "{name} campuses"),
  cityClimate: L("{name}的天气", "Weather in {name}"),
  arrivedYear: L("{n} 年入学", "Arrived {n}"),
  program: L("专业", "Program"),
  level: L("层次", "Level"),
  settingsTitle: L("编辑资料", "Edit profile"),
  memberMissing: L("未找到成员", "Member not found"),
  testTitle: L("[测试版] 你好校园 NihaoCampus · 来华留学生的城市与校区指南", "[Test] NihaoCampus · a campus guide for students coming to China"),
  testTitleTemplate: L("%s · [测试版] 你好校园 NihaoCampus", "%s · [Test] NihaoCampus"),
  testDescription: L(
    "测试预览：当前城市、价格、成员及社区内容均为演示数据，请勿用于申请、签证或生活决策。",
    "Test preview: cities, prices, members and community posts are demo data. Do not use them for applications, visas, or life decisions.",
  ),
  progressOf: L("{done} / {total}", "{done} / {total}"),
  markThisStep: L("标一下你哪天去", "Mark the day you'll go"),
  markDate: L("计划日期", "Planned date"),
  markSave: L("标一下", "Mark it"),
  markSaving: L("正在保存…", "Saving…"),
  markedPlanned: L("已标计划", "Marked as planned"),
  markedDone: L("已完成", "Done"),
  markDone: L("办完了", "I finished this"),
  unmark: L("取消标记", "Remove mark"),
  nPlanning: L("本周有 {n} 人计划去办", "{n} people marked this week"),
  nNotes: L("{n} 条经验", "{n} notes"),
  leaveNote: L("留一条经验", "Leave a signed note"),
  noteReason: L(
    "经验必须署名，后来的人才能知道这话是谁写的。",
    "A note has to carry your name so the next student knows who wrote it.",
  ),
  noteBody: L("你刚办完的时候，有什么是清单没写到的？", "What did the checklist miss when you actually did this?"),
  notePublish: L("发布经验", "Publish note"),
  noteFailed: L("没保存住，再试一次", "That did not save. Try again."),
  markFailed: L("没标上，再试一次", "That mark did not save. Try again."),
} as const;

export function fill(template: Localized, locale: import("@/lib/locale").Locale, vars: Record<string, string | number>): string {
  let out = template[locale];
  for (const [key, value] of Object.entries(vars)) {
    out = out.replaceAll(`{${key}}`, String(value));
  }
  return out;
}
